name: super_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sizer: ^2.0.15
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17

  # icon and image
  cached_network_image: ^3.4.1
  iconsax: ^0.0.8

  # slide image
  carousel_slider: ^5.0.0

  # grid view
  flutter_staggered_grid_view: ^0.7.0

  # navbar
  contained_tab_bar_view: ^0.8.0

  # local storage
  share_plus: ^10.0.2
  shared_preferences: ^2.3.5

  # form
  form_builder_validators: ^11.0.0
  flutter_form_builder: ^9.3.0
  pattern_formatter: ^4.0.0

  # top_snackbar
  top_snackbar_flutter: ^3.1.0

  # contact service
  # contacts_service: ^0.6.3

  # animation
  loading_animation_widget: ^1.3.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.1
  flutter_spinkit: ^5.2.1

  # dot
  dotted_line: ^3.2.3

  # qr code and bill
  keyboard_attachable: ^2.2.0
  saver_gallery: ^4.0.1
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5

  # api
  dio: ^5.7.0
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0

  # package info
  package_info_plus: ^8.1.3
  device_info_plus: ^11.3.0
  animation_list: ^3.1.0
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  # logo bank

  # pin code
  pinput: ^5.0.1
  # socket
  socket_io_client: ^3.0.2

  # credit card
  u_credit_card: ^1.4.0
  # dropdown
  dropdown_button2: ^2.3.9
  # web view
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

  # refresh
  pull_to_refresh: ^2.0.0

  photo_view: ^0.15.0
  image: ^4.5.2
  image_cropper: ^9.0.0
  table_calendar: ^3.1.3
  syncfusion_flutter_calendar: ^28.2.4
  flutter_animate: ^4.5.2

  animate_do: ^3.3.4
  # slider
  syncfusion_flutter_sliders: ^28.2.5
  local_auth: ^2.3.0
  # image_gallery_saver: ^2.0.3

  # cache
  flutter_cache: ^0.1.0

  
  
  #chart
  percent_indicator: ^4.2.2

  intl: ^0.19.0
  collection: ^1.19.0

  #widget
  sliding_up_panel: ^2.0.0+1
  flutter_slidable: ^3.1.2
  pin_code_fields: ^8.0.1
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/lang/
    - assets/animation/
    - assets/background/
    - assets/boarding/
    - assets/images/
    - assets/history/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
