name: super_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sizer: ^2.0.15
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17

  # icon and image
  cached_network_image: ^3.2.3
  iconsax: ^0.0.8

  # slide image
  carousel_slider: ^5.0.0

  # grid view
  flutter_staggered_grid_view: ^0.7.0

  # navbar
  contained_tab_bar_view: ^0.8.0

  # local storage
  share_plus: ^10.0.2
  shared_preferences: ^2.3.5

  # form
  form_builder_validators: ^11.0.0
  flutter_form_builder: ^9.3.0
  pattern_formatter: ^4.0.0

  # top_snackbar
  top_snackbar_flutter: ^3.1.0

  # contact service
  contacts_service: ^0.6.3

  # animation
  loading_animation_widget: ^1.3.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/lang/
    - assets/animation/
    - assets/background/
    - assets/boarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
